# Parameters used for generation of embeddings
# Make sure `load` is specified somewhere else
{
  # Don't use kv cache
  "recompute": true,

  # input/output file
  "sample-input-file": "quotes_medium.jsonl",
  "sample-output-file": "sample_embeddings.npy",
}
